name: simpoir-taskwarrior3
base: core24
version: '0.0'
adopt-info: taskwarrior
summary: Command line task list management
description: |
  Taskwarrior is a sophisticated command line todo list and task
  manager with a lot of features:
  * colorful tabbed output
  * feature rich search function
  * tags
  * statistics
  * Getting Things Done compatible
  * interactive editing of items in text editor
grade: devel
confinement: strict
website:
  - "https://github.com/GothenburgBitFactory/taskwarrior"
  - "https://github.com/simpoir/taskwarrior3-snap"

apps:
  task:
    command: usr/local/bin/task
    plugs:
      - network
  man:
    command: man.sh

parts:
  scripts:
    source: .
    plugin: dump

  taskwarrior:
    source-type: git
    source: https://github.com/GothenburgBitFactory/taskwarrior
    plugin: cmake
    build-packages:
      - uuid-dev
    build-snaps:
      - rustup
    override-build: |
      rustup default stable
      snapcraftctl build
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags --no-abbrev)"
      craftctl set version="$(git describe --tags|sed 's/^v//')"
      sed -i 's:${CMAKE_INSTALL_PREFIX}:/snap/'"$(craftctl get name)"'/current/usr/local:' cmake.h.in
